FROM python:3.11-slim

RUN pip install uv
WORKDIR /app
COPY . .

RUN uv pip install -r requirements.txt

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
