services:
  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # pour la persistance du modèle
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_models:
