FROM ubuntu:22.04

# Installer Ollama et dépendances
RUN apt-get update && apt-get install -y curl sudo
RUN curl -fsSL https://ollama.com/install.sh | sh

# Copier ton fichier Modelfile
COPY Modelfile /Modelfile

# Démarrage avec creation du modèle au premier lancement
CMD bash -c "\
    if ! ollama list | grep -q model_llama_3b; then \
        echo 'Création du modèle model_llama_3b...'; \
        ollama create model_llama_3b -f /Modelfile; \
    fi && \
    echo 'Démarrage de Ollama...' && \
    ollama serve"
