FROM ubuntu:22.04

# Installer Ollama et dépendances
RUN apt-get update && apt-get install -y curl sudo
RUN curl -fsSL https://ollama.com/install.sh | sh

# Copier le Modelfile
COPY Modelfile /Modelfile

CMD bash -c "\
    ollama serve & \
    echo '🕒 Démarrage du serveur Ollama...' && \
    until curl -s http://localhost:11434/ > /dev/null; do \
        echo ' En attente du serveur Ollama...'; \
        sleep 1; \
    done && \
    echo 'Serveur Ollama prêt.' && \
    if ! ollama list | grep -q model_llama_3b; then \
        echo 'Création du modèle model_llama_3b...'; \
        ollama create model_llama_3b -f /Modelfile; \
    else \
        echo ' Modèle model_llama_3b déjà existant.'; \
    fi && \
    wait"



